server:
  ssl:
    enabled: false
    key-store: KEYSTORE
    key-store-password: KEYSTORE_PASS
    key-store-type: pkcs12
    key-alias: springboot
  port: 8080

spring:
    servlet:
        multipart:
          enabled: false
            
app:
  rootDir: /srv/silkspinner
  
storage:
  audioFiles: /mnt/filepile/0_originals/audiomoth
  dataFiles: /srv/silkspinner/store