server:
  ssl:
    key-store: KEYSTORE
    key-store-password: KEYSTORE_PASS
    key-store-type: pkcs12
    key-alias: springboot
  port: 8443

spring:
    servlet:
        multipart:
            max-file-size: 10GB
            max-request-size: 10GB
            file-size-threshold: 100MB
            location: /data/app/temp
            
app:
  rootDir: /data/app
  
storage:
    diskLocation: /data/app/store