server:
  ssl:
    key-store: KEYSTORE
    key-store-password: KEYSTORE_PASS
    key-store-type: pkcs12
    key-alias: springboot
  port: 8443

spring:
    servlet:
        multipart:
            max-file-size: 1GB
            max-request-size: 1GB

storage:
    diskLocation: /data/app/store