server:
  ssl:
    enabled: false
    key-store: KEYSTORE
    key-store-password: KEYSTORE_PASS
    key-store-type: pkcs12
    key-alias: springboot
  port: 8080
           
app:
  rootDir: /data/app
  
storage:
  dataFiles: /data/app/store