server:
  ssl:
    enabled: false
    key-store: KEYSTORE
    key-store-password: KEYSTORE_PASS
    key-store-type: pkcs12
    key-alias: springboot
  port: 8080

spring:
    servlet:
        multipart:
          enabled: false
            
app:
  rootDir: /data/app
  
storage:
  ftpHost: 10.0.0.1
  dataFiles: /shares/filepile/0_originals/audiomoth
  analysisStore: /data/app/store
  tempStore: /data/app/temp

auth:
  username: admin
  password: tVaI0l30AcKX